import { ProductDetail } from "@/types/product"

export const ProductDetaildata = () => {
    const mockData: ProductDetail = {
        'bts1': { src: '/Bts/bts1.png', nameProduct: 'Face Keyring', price: '790', Remark: 'Shipped from Korea to Thailand' },
        'bts2': { src: '/Bts/bts2.png', nameProduct: 'Lucky Draw (Random)', price: '390', Remark: 'Shipped from Korea to Thailand' },
        'bts3': { src: '/Bts/bts3.png', nameProduct: 'Knit Cardigan (Beige)', price: ' 5,990', Remark: 'Shipped from Korea to Thailand' },
        'bts4': { src: '/Bts/bts4.png', nameProduct: '[CAPSULE ALBUM Vol.1] \nule Merch Full Package', price: '1490', Remark: 'Shipped from Korea to Thailand' },
        'twm1': { src: '/Tmw/twm1.png', nameProduct: 'Photocard Holder', price: '790', Remark: 'Shipped from Korea to Thailand' },
        'twm2': { src: '/Tmw/twm2.png', nameProduct: 'Lucky Draw (Random)', price: '390', Remark: 'Shipped from Korea to Thailand' },
        'twm3': { src: '/Tmw/twm3.png', nameProduct: 'Lunch Box', price: '980', Remark: 'Shipped from Korea to Thailand' },
        'twm4': { src: '/Tmw/twm4.png', nameProduct: 'OFFICIAL LIGHT STICK STAND', price: '1490', Remark: 'Shipped from Korea to Thailand' },
        'en1': { src: 'En/en1.png', nameProduct: 'Instant Photo Set', price: '490', Remark: 'Shipped from Korea to Thailand' },
        'en2': { src: 'En/en2.png', nameProduct: 'Printed Photo', price: '100', Remark: 'Shipped from Korea to Thailand' },
        'en3': { src: 'En/en3.png', nameProduct: 'Rain Poncho', price: '1690', Remark: 'Shipped from Korea to Thailand' },
        'en4': { src: 'En/en4.png', nameProduct: 'S/S T-shirt (MINE)', price: '1490', Remark: 'Shipped from Korea to Thailand' },
        'st1': { src: '/ST/ST1.png', nameProduct: 'SEVENTEEN UNIT \nPHOTOBOOK ‘EPISODE C’', price: '1080', Remark: 'Shipped from Korea to Thailand' },
        'st2': { src: '/ST/ST2.png', nameProduct: 'SEVENTEEN UNIT \nPHOTOBOOK ‘EPISODE D’', price: '1080', Remark: 'Shipped from Korea to Thailand' },
        'st3': { src: '/ST/ST3.png', nameProduct: 'SEVENTEEN UNIT PHOTOBOOK ‘EPISODE C,D SET', price: '1990', Remark: 'Shipped from Korea to Thailand' },
        'st4': { src: '/ST/ST4.png', nameProduct: 'NANA bnb with SEVENTEEN 2025 KIT', price: '1490', Remark: 'Shipped from Korea to Thailand' },
        'nct1': { src: '/Nct/Nct1.png', nameProduct: '[Go Back To The Future] \n(Digipack Ver.) Random', price: '690', Remark: 'Shipped from Korea to Thailand' },
        'nct2': { src: '/Nct/Nct2.png', nameProduct: '[Go Back To The Future] \n(Ultimate Park Ver.)', price: '890', Remark: 'Shipped from Korea to Thailand' },
        'nct3': { src: '/Nct/Nct3.png', nameProduct: 'MINI FANLIGHT KEYRING', price: '690', Remark: 'Shipped from Korea to Thailand' },
        'nct4': { src: '/Nct/Nct4.png', nameProduct: 'OFFICIAL LIGHT TOK', price: '990', Remark: 'Shipped from Korea to Thailand' },
        'hot1': { src: '/hot/hot1.png', nameProduct: 'JIN’ s Bear Pouch Charm', price: '1790', Remark: 'Shipped from Korea to Thailand' },
        'hot2': { src: '/hot/hot2.png', nameProduct: 'Bear Pattern Pouch (Mint)', price: '1890', Remark: 'Shipped from Korea to Thailand' },
        'hot3': { src: '/hot/hot3.png', nameProduct: 'Bear Pattern Pouch (Pink)', price: '1890', Remark: 'Shipped from Korea to Thailand' },
        'hot4': { src: '/hot/hot4.png', nameProduct: 'Quilting Tote Bag (Pink)', price: '2490', Remark: 'Shipped from Korea to Thailand' },
        'hot5': { src: '/hot/hot5.png', nameProduct: 'Quilting Tote Bag (Mint)', price: '2490', Remark: 'Shipped from Korea to Thailand' },
        'hot6': { src: '/hot/hot6.png', nameProduct: 'Cardigan (Pink)', price: '4900', Remark: 'Shipped from Korea to Thailand' },
        'hot7': { src: '/hot/hot7.png', nameProduct: 'Cardigan (Mint)', price: '4900', Remark: 'Shipped from Korea to Thailand' },
        'hot8': { src: '/hot/hot8.png', nameProduct: 'Bear Pattern Long Pants (Pink)', price: '3290', Remark: 'Shipped from Korea to Thailand' },
        'pd1': { src: '/all/pd1.png', nameProduct: '[CAPSULE ALBUM Vol.1] Capsule Merch Full Package', price: '1490', Remark: 'Shipped from Korea to Thailand' },
        'pd2': { src: '/all/pd2.png', nameProduct: 'ARMY MEMBERSHIP GIFT', price: '0', Remark: 'Shipped from Korea to Thailand' },
        'pd3': { src: '/all/pd3.png', nameProduct: '2025 BTS FESTA : CAPSULE ALBUM Vol.1', price: '690', Remark: 'Shipped from Korea to Thailand' },
        'pd4': { src: '/all/pd4.png', nameProduct: 'ARMY MEMBERSHIP', price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd5': { src: '/all/pd5.png', nameProduct: '#RUNSEOKJIN_EP.TOUR in JAPAN HD Single-view + GIFT', price: '1690', Remark: 'Shipped from Korea to Thailand' },
        'pd6': { src: '/all/pd6.png', nameProduct: '[RAFFLE EVENT] PERMISSION TO DANCE ON STAGE - LIVE (Set) + PERMISSION TO DANCE - SEOUL (DIGITAL CODE)', price: '2290', Remark: 'Shipped from Korea to Thailand' },
        'pd7': { src: '/all/pd7.png', nameProduct: 'PERMISSION TO DANCE ON STAGE - LIVE (Set) + PERMISSION TO DANCE - SEOUL (DIGITAL CODE)', price: '2290', Remark: 'Shipped from Korea to Thailand' },
        'pd8': { src: '/all/pd8.png', nameProduct: 'PERMISSION TO DANCE ON STAGE - LIVE (Set)', price: '1490', Remark: 'Shipped from Korea to Thailand' },
        'pd9': { src: '/all/pd9.png', nameProduct: 'PERMISSION TO DANCE ON STAGE - LIVE (Random)', price: '890', Remark: 'Shipped from Korea to Thailand' },
        'pd10': { src: '/all/pd10.png', nameProduct: 'PLUSH minini BAND', price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd11': { src: '/all/pd11.png', nameProduct: 'MERCH BOX #18', price: '0', Remark: 'Shipped from Korea to Thailand' },
        'pd12': { src: '/all/pd12.png', nameProduct: '#RUNSEOKJIN_EP.TOUR in JAPAN HD Single-view', price: '1690', Remark: 'Shipped from Korea to Thailand' },
        'pd13': { src: '/all/pd13.png', nameProduct: `5th Album 'HAPPY BURSTDAY' (Random)`, price: '890', Remark: 'Shipped from Korea to Thailand' },
        'pd14': { src: '/all/pd14.png', nameProduct: `5th Album ‘HAPPY BURSTDAY’ KiT Ver. (Option)`, price: '920', Remark: 'Shipped from Korea to Thailand' },
        'pd15': { src: '/all/pd15.png', nameProduct: `5th Album ‘HAPPY BURSTDAY’ KiT Ver. (Set)`, price: '1590', Remark: 'Shipped from Korea to Thailand' },
        'pd16': { src: '/all/pd16.png', nameProduct: `[YouTube GIFT]DESIRE : \nUNLEASH (Random)`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd17': { src: '/all/pd17.png', nameProduct: `[YouTube GIFT]DESIRE : UNLEASH (Set)`, price: '1790', Remark: 'Shipped from Korea to Thailand' },
        'pd18': { src: '/all/pd18.png', nameProduct: `DESIRE : UNLEASH (Set)`, price: '1790', Remark: 'Shipped from Korea to Thailand' },
        'pd19': { src: '/all/pd19.png', nameProduct: `DESIRE : UNLEASH (Random)`, price: '570', Remark: 'Shipped from Korea to Thailand' },
        'pd20': { src: '/all/pd20.png', nameProduct: `[VIDEO CALL FANSIGN] 'The Star Chapter: TOGETHER' (Set)`, price: '1790', Remark: 'Shipped from Korea to Thailand' },
        'pd21': { src: '/all/pd21.png', nameProduct: `[OFFLINE FANSIGN] 'The Star Chapter: TOGETHER' (Random)`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd22': { src: '/all/pd22.png', nameProduct: `[OFFLINE FANSIGN] 'The Star Chapter: TOGETHER' (Set)`, price: '1790', Remark: 'Shipped from Korea to Thailand' },
        'pd23': { src: '/all/pd23.png', nameProduct: `[VIDEO CALL FANSIGN] 'The Star Chapter: TOGETHER' (Random)`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd24': { src: '/all/pd24.png', nameProduct: `#RUNSEOKJIN_EP.TOUR in JAPAN HD Single-view`, price: '1690', Remark: 'Shipped from Korea to Thailand' },
        'pd25': { src: '/all/pd25.png', nameProduct: `1st FULL ALBUM [DRIP] ZIP LOCK Ver.`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd26': { src: '/all/pd26.png', nameProduct: `[LUCKY DRAW] 1st FULL ALBUM [DRIP] ZIP LOCK Ver.`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd27': { src: '/all/pd27.png', nameProduct: `1st FULL ALBUM [DRIP] JEWEL CASE Ver.`, price: '690', Remark: 'Shipped from Korea to Thailand' },
        'pd28': { src: '/all/pd28.png', nameProduct: `[LUCKY DRAW] 1st FULL ALBUM [DRIP] JEWEL CASE Ver.`, price: '690', Remark: 'Shipped from Korea to Thailand' },
        'pd29': { src: '/all/pd29.png', nameProduct: `[LUCKY DRAW] 1st FULL ALBUM [DRIP] YG TAG ALBUM Ver.`, price: '590', Remark: 'Shipped from Korea to Thailand' },
        'pd30': { src: '/all/pd30.png', nameProduct: `1st FULL ALBUM [DRIP] YG TAG ALBUM Ver`, price: '590', Remark: 'Shipped from Korea to Thailand' },
        'pd31': { src: '/all/pd31.png', nameProduct: `SPECIAL MINI ALBUM [PLEASURE] [YELLOW & GREEN VER.] Set`, price: '1090', Remark: 'Shipped from Korea to Thailand' },
        'pd32': { src: '/all/pd32.png', nameProduct: `SPECIAL MINI ALBUM [PLEASURE] [YELLOW & GREEN VER.] Option`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd33': { src: '/all/pd33.png', nameProduct: `SPECIAL MINI ALBUM [PLEASURE] [BLUE VER.] Set`, price: '3190', Remark: 'Shipped from Korea to Thailand' },
        'pd34': { src: '/all/pd34.png', nameProduct: `SPECIAL MINI ALBUM [PLEASURE] [BLUE VER.] Option`, price: '590', Remark: 'Shipped from Korea to Thailand' },
        'pd35': { src: '/all/pd35.png', nameProduct: `THE JOURNEY STAR CORE CLOSET - HOODIE CAPE`, price: '1990', Remark: 'Shipped from Korea to Thailand' },
        'pd36': { src: '/Nct/Nct1.png', nameProduct: `[Go Back To The Future] (Digipack Ver.) Random`, price: '690', Remark: 'Shipped from Korea to Thailand' },
        'pd37': { src: '/Nct/Nct1.png', nameProduct: `[Go Back To The Future] (Ultimate Park Ver.)`, price: '890', Remark: 'Shipped from Korea to Thailand' },
        'pd38': { src: '/Nct/Nct1.png', nameProduct: `[Go Back To The Future] (I AM THE FUTURE Ver.)`, price: '890', Remark: 'Shipped from Korea to Thailand' },
        'pd39': { src: '/Nct/Nct1.png', nameProduct: `[Go Back To The Future] (Hoverboard Ver.) (SMART ALBUM)`, price: '690', Remark: 'Shipped from Korea to Thailand' },
        'pd40': { src: '/Nct/Nct1.png', nameProduct: `[Go Back To The Future] (Digipack Ver.) Set`, price: '1790', Remark: 'Shipped from Korea to Thailand' },
        'pd41': { src: '/all/pd36.png', nameProduct: `1st FULL ALBUM [DRIP] BINDER Ver.`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd42': { src: '/all/pd36.png', nameProduct: `[LUCKY DRAW] 1st FULL ALBUM [DRIP] BINDER Ver.`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd43': { src: '/all/pd37.png', nameProduct: `[LUCKY DRAW] 1st FULL ALBUM [DRIP] ZIP LOCK & BINDER Ver. Set + JEWEL CASE Ver. (2)`, price: '2090', Remark: 'Shipped from Korea to Thailand' },
        'pd44': { src: '/all/pd38.png', nameProduct: `Single [Dirty Work] (Dirty Crew Ring Ver.)`, price: '4790', Remark: 'Shipped from Korea to Thailand' },
        'pd45': { src: '/all/pd39.png', nameProduct: `Single [Dirty Work] (Dirty Code Ver.) (Random)`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd46': { src: '/all/pd40.png', nameProduct: `Single [Dirty Work] (Dirty Case Ver.) (Random)`, price: '1090', Remark: 'Shipped from Korea to Thailand' },
        'pd47': { src: '/all/pd41.png', nameProduct: `Single [Dirty Work] (Dirty Worker Ver.)`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd48': { src: '/all/pd42.png', nameProduct: `The 5th Mini Album [Whiplash] (BEAT Ver.) (Random)`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd49': { src: '/all/pd43.png', nameProduct: `3rd Mini Album 'Caligo Pt.1' (Vanguard Ver.) Random`, price: '790', Remark: 'Shipped from Korea to Thailand' },
        'pd50': { src: '/all/pd44.png', nameProduct: `3rd Mini Album 'Caligo Pt.1' (Vanguard Ver.) Set`, price: '2790', Remark: 'Shipped from Korea to Thailand' },
    }
    return mockData
}
